package cn.mj.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-07-12T21:25:29.911+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.service.ecps.mj.cn/", name = "EbWsItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWsItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.service.ecps.mj.cn/", className = "cn.mj.ecps.stub.PublishItem")
    @WebMethod
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.service.ecps.mj.cn/", className = "cn.mj.ecps.stub.PublishItemResponse")
    public String publishItem(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Long arg1
    );
}
